In [1]:
import numpy as np

In [2]:
import pandas as pd

 ## Numpy Array Operations:
 1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
2. Inspection and Properties:
● Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

3. Array Operations:
● Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.
4. Array Slicing and Indexing:
● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

5. Create a 2D Array:
Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

6. Inspect and Slice the 2D Array:
● Inspect and print the shape, data type, and total number of elements in the
temperatures array.
● Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [4]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [5]:
temperatures_w1.shape

(7,)

In [6]:
temperatures_w1.dtype

dtype('float64')

In [7]:
temperatures_w1.size

7

In [8]:
temperatures_w1=Fahrenheit = (temperatures_w1 * 9/5) + 32
temperatures_w1

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [32]:
temperatures_w1.max()

np.float64(78.98)

In [33]:
temperatures_w1.min()

np.float64(69.44)

In [34]:
temperatures_w1.mean()

np.float64(74.37714285714286)

In [35]:
temperatures_w1[0:3]

array([72.5 , 77.54, 69.44])

In [36]:
temperatures_w1[-2:]

array([76.64, 71.42])

In [37]:
temperatures_w1[2:5]

array([69.44, 74.12, 78.98])

In [9]:
week1=[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
week2=[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
temperatures=np.array([week1,week2])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [10]:
temperatures.shape

(2, 7)

In [11]:
temperatures.dtype

dtype('float64')

In [56]:
temperatures.size

14

In [145]:
temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [146]:
temperatures[1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [65]:
temperatures[0][-2:],temperatures[1][-2:]

(array([24.8, 21.9]), array([22.8, 20.1]))

## Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'
2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.
● Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.
● Use the iloc accessor to retrieve the mark of the 3rd rank student.
● Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.
3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.
● Remove the entry corresponding to the last rank from the Series.
● Compute the CGPA by dividing each mark in the Series by 10.

In [44]:
marks=pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [21]:
marks.iloc[0]

np.int64(95)

In [22]:
marks.loc["Rank1":"Rank3"]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [23]:
marks.iloc[2]

np.int64(89)

In [48]:
marks[marks>90]


Rank1    95
Rank2    92
dtype: int64

In [29]:
marks.loc['Rank1']=100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [45]:
marks=marks.drop('Rank5')
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
dtype: int64

In [180]:
cgpa=marks/10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64


## 1. Creating Pandas DataFrame:
● Create a Pandas DataFrame named transactions with the following data:
➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

2. Data Exploration:
● Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.
● Display only the 'ProductCategory' and 'Amount' columns.
● Retrieve the last 3 columns of the DataFrame using iloc or loc.
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
● Find the value counts for the 'ProductCategory' column.
● Find the unique values in the 'Region' column.
● Group by 'Region' and find the mean amount for each region.
3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
● Add a new column 'Discount' by calculating 10% of the 'Amount'.
● Remove the row with TransactionID 109.
● Delete the 'Discount' column from the DataFrame.

In [191]:
data={"TransactionID":[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],"ProductCategory":['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],"Region":['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],"Amount":[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}

In [173]:
transactions=pd.DataFrame(data)
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [174]:
print("Head:\n",transactions.head())
print("Tail:\n",transactions.tail())
print("Shape:\n",transactions.shape)
print("Columns Name:\n",transactions.columns)
print("Data types:\n",transactions.dtypes)

Head:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
Tail:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape:
 (10, 4)
Columns Name:
 Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')
Data types:
 TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object


In [175]:
transactions[['ProductCategory','Amount']]

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [165]:
transactions.loc[:,'ProductCategory':'Amount']

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [166]:
transactions.loc[(transactions['Region']=='North')&(transactions['Amount']>200)]

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


In [131]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [132]:
transactions['Region'].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [167]:
transactions.groupby('Region')["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [176]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [192]:
transactions['Discount']=transactions['Discount']=transactions['Amount']*.10
transactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [185]:
transactions=transactions[transactions['TransactionID']!=109]
transactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [193]:
transactions=transactions.drop(['Discount'],axis=1)
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400
